Initial tabular classification Santander
Lightning-AI/tutorials pull request #124
Opened 2021-12-13 21:20 UTC by PabloAMC

# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

2021-12-13 21:35 UTC, Borda submitted a review, later dismissed
could you pls provide metafile with required details :rabbit:

2021-12-21 12:12 UTC, Borda reviewed
hi, seems you are accidentally changing some other files in Flash turorials

2021-12-21 12:17 UTC, PabloAMC commented
> hi, seems you are accidentally changing some other files in Flash turorials

I changed the name of the electricity_forecasting folder to tabular_forecasting. I believe that might be much more informative.

2021-12-30 09:10 UTC, Borda reviewed
seems that you included unrelated images from the tutorial

2021-12-30 09:10 UTC, Borda commented on flash_tutorials/tabular_classification/.meta.yml
> +  - CPU
```suggestion
  - CPU
datasets:
  kaggle:
    - santander-customer-transaction-prediction
```
missing data: https://www.kaggle.com/c/santander-customer-transaction-prediction

2021-12-30 09:10 UTC, Borda commented on flash_tutorials/tabular_classification/santander.py
> +path_santander = os.path.join(data_path, "santander")
```suggestion
path_santander = os.path.join(data_path, "santander-customer-transaction-prediction")
```

2021-12-30 14:10 UTC, PabloAMC commented
Why do we get error
```
python -m pytest flash_tutorials/tabular_classification/santander.ipynb -v --nbval
deactivate
rm -rf flash_tutorials/tabular_classification/venv
401 - Unauthorized
Error: Process completed with exit code 1.
```
?

2022-01-07 13:30 UTC, Borda requested changes
pls, remove images that are not related to this tutorial...

2022-03-09 19:57 UTC, Borda commented
@PabloAMC seems like some variables in the notebook are not defined... mind checking the failing test?

2024-07-23 08:35 UTC, closed without merging

2024-07-23 08:35 UTC, Borda commented
we may not promote Flash examples as it was archived some time ago, apology nd thank you for all you help :rabbit: